---
- hosts: pve
  remote_user: root
  vars_files:
   - host_vars/infra/km01.yml

  roles: 
   - spinvm

- hosts: pve
  remote_user: root
  vars_files:
   - host_vars/infra/kn01.yml

  roles:
   - spinvm

- hosts: pve
  remote_user: root
  vars_files:
   - host_vars/infra/kn02.yml

  roles:
   - spinvm

- hosts: pve
  remote_user: root
  vars_files:
   - host_vars/infra/kn03.yml

  roles:
   - spinvm
