---
node: pve2
api_user: root@pam
api_password: BSm05W4NT3d
api_host: 10.0.0.21
vmid: 108
vmhostname: monit02
vcpus: 2
cores: 2
memory: 2048
virtual_disk: '{"virtio0":"local1:100,format=qcow2"}'
virtual_network: '{"net0":"virtio=00:A1:00:00:00:C2,bridge=vmbr0,rate=1000"}'
