---
apache_enablerepo: ""

apache_listen_ip: "*"
apache_listen_port: "80"
apache_listen_port_ssl: "443"

apache_create_vhosts: "true"
apache_vhosts_filename: "{{  domain_name  }}.conf"
apache_vhosts_template: "{{  domain_name  }}.conf.j2"


apache_global_vhost_settings: |
   DirectoryIndex index.php index.html

apache_vhosts:
  - servername: "{{  domain_name  }}"
    documentroot: "{{  document_root  }}"

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymlinks"

apache_vhosts_ssl: 
   - servername: "{{  domain_name  }}"
     documentroot: "{{  document_root  }}"
     certificate_file: "{{  ssl_tls_directory  }}/{{  domain_name  }}.crt"
     certificate_key_file: "{{  ssl_tls_directory  }}/{{  domain_name }}.pem"

apache_ignore_missing_ssl_certificate: true

apache_ssl_protocol: "All -SSLv2 -SSLv3"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"
