---
- name: Install httpd and mod_ssl on Web Servers
  yum:
   name: "{{  item  }}"
   update_cache: yes
   state: latest
  with_items:
    - httpd
    - mod_ssl

- name: Start and enable the service
  systemd:
   name: httpd
   state: started
   enabled: yes

- name: Ensure python OpenSSL dependencies are installed.
  pip:
    name: pyOpenSSL
    state: present

- name: Ensure directory exists for local self-signed TLS certs.
  file:
    path: "{{ ssl_tls_directory  }}"
    state: directory

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: "{{  ssl_tls_directory  }}/{{ domain_name }}.pem"

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: "{{  ssl_tls_directory  }}/{{ domain_name }}.csr"
    privatekey_path: "{{  ssl_tls_directory  }}/{{ domain_name }}.pem"
    common_name: "{{ domain_name }}"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{  ssl_tls_directory  }}/{{ domain_name }}.crt"
    privatekey_path: "{{  ssl_tls_directory  }}/{{ domain_name }}.pem"
    csr_path: "{{  ssl_tls_directory  }}/{{ domain_name }}.csr"
    provider: selfsigned

- name: Enable httpd modules
  apache2_module:
    name: "{{  item  }}"
    state: present
  with_items:
     - ssl
     - rewrite
  notify: restart apache

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "/etc/httpd/conf.d/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Create document root
  file:
    path: "{{  document_root  }}"
    state: directory

- name:  Remove openssl python dependencies
  pip: 
    name: pyOpenSSL
    state: absent
