---
- name: Add Docker Repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install Containerd manually (CentOS8 repositories do not have latest version)
  yum:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    state: present

- name: Install Docker-CE
  yum:
    name: docker-ce
    state: present
