---
- name: Add Ansible user and SSH key to remote system
  hosts: unconfigured
  become: no
  become_method: su

  tasks:

  - debug:
      msg: "{{ item }}"
    with_items:
      - "NOTE! You must execute this playbook with the --ask-become-pass, --ask-pass, and -u <user> options."
      - "Please ensure you have done 'export ANSIBLE_HOST_KEY_CHECKING=False' or this play will fail."

  - name: Add ansible user
    user:
      name: ansible
      comment: Ansible management user

  - name: Check for SSH configuration directory
    file:
      path: /home/ansible/.ssh
      state: directory
      owner: ansible
      group: ansible
      mode: '700'

  - name: Add ansible SSH key
    copy:
      src: /home/ansible/.ssh/id_rsa.pub
      dest: /home/ansible/.ssh/authorized_keys
      owner: ansible
      group: ansible

  - name: Add ansible user to sudoers
    lineinfile:
      dest: /etc/sudoers.d/admins
      line: "{{ item }}"
      create: yes
    with_items:
      - "ansible     ALL=(ALL)       NOPASSWD:ALL"
